package lk.petalpink.petalpink.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

@AllArgsConstructor
@NoArgsConstructor
@Data
public class ProductionDTO {

    private Integer productionId;

    /** e.g. "PRD-0001" — generated by the service */
    private String refNo;

    /** Manufacturing date */
    private LocalDate manDate;

    /** Expiry date (nullable) */
    private LocalDate expDate;

    /** The finished / produced item */
    private Integer itemId;
    private String  itemName;

    /** FK → pos_main_unit_type_tb */
    private Integer unitType;
    private String  unitTypeName;

    /** Quantity produced */
    private Double qty;

    /** Wastage quantity */
    private Double wastage;

    private Integer status;
    private Integer userId;
}